### ISSUE TITLE
[SUGGEST] 부스와 이벤트의 유저 서비스 클래스명 변경 제안

### ISSUE THREAD

**Issue by muncool39** [Project-OpenBook/openbook-server#114]
## Description

기존 부스와 이벤트의 User~Service 의 네이밍 변경에 대한 의견입니다!

User~Service가 Admin, EventManager 등도 공통으로 사용하는 기능이라고 생각되어서 user 도메인에서 사용하듯이 Common 을 붙여서 사용하는건 어떨까 하는 생각이 들어서 작성했습니다.

**현재 서비스 클래스 명**
- UserBoothService
- UserEventService
- UserCommonService

**제안하는 방식**
- BoothCommonService
- EventCommonService
- UserCommonService

또는 
- Common~Service (현재 AdminEventService 등 권한을 앞에 두는 방식이기 때문에)
## Additional context

- 그대로 User~로 사용해도 괜찮다고 생각합니다!
꼭 바꿔야된다기보단 이런식으로 통합해도 괜찮겠다는 생각이 든 김에 적어봤습니다.
쉽게 바꿀 수 있는 내용이라 어떤 명칭이 괜찮을지 충분히 생각해본 후에 결정해봐도 좋을 것 같아요!😀
- 네이밍 외에도 패키지 등 다른 의견 등 생각나시는 내용 있으시면 많이 말씀해주세요!

**Comment by gitseoyeon** [comment]
공통으로 사용되는 서비스 같은 경우에는 User 뿐만 아니라 그 외의 권한을 가진 사용자도 사용하는 서비스 이기 때문에 User~를 사용하기 보다 말씀하신 것처럼 common을 사용하면 더 명확해지겠네요! 저는 좋다고 생각합니다 !

**Comment by muncool39** [comment]
변경 완료되었습니다~
