### ISSUE TITLE
[FEAT] 행사 부스 검색

### ISSUE THREAD

**Issue by gitseoyeon** [Project-OpenBook/openbook-server#123]
## Description

- 검색어를 입력했을 때 행사명, 부스명, 행사 해시태그, 부스 해시태그 별로 4개의 데이터 조회
## TODO

- [ ] 각 종류 별 나타나는 데이터 값들을 담을 dto 작성

**Comment by muncool39** [comment]
이거 궁금한 점이 있는데, 프론트에서 4종류의 api를 검색 시 한번에 호출해서 각 결과에서 4개씩 뽑아서 사용하는 방법을 사용하는건 안좋을까요?

**Comment by gitseoyeon** [comment]
다음 회의때 프론트 분들께 여쭤보고 결정해도 좋겠네요! 😊

**Comment by muncool39** [comment]
회의 당시, 한번에 호출하는 방향으로 결정되어 해당 이슈는 닫도록 하겠습니다!
