### ISSUE TITLE
[SUGGEST] 프로젝트 패키지 구조 리팩터링 제안

### ISSUE THREAD

**Issue by muncool39** [Project-OpenBook/openbook-server#199]
## Description

현재 컨트롤러나 서비스가 권한 별로 나누어져 있는 것을 계층이나 도메인 별로 나누는 구조를 제안합니다.

생각한 방법은 다음 두 가지가 있습니다.
1. 계층 별 분리 후 도메인 별 분리
2. 도메인 별 분리 후 계층 별 분리 (현재 방식)

**첫 번째 구조 예시**
```
com.example.projectname
├── domain
│   ├── booth
│   ├── event
│   ├── alarm
│   └── user
├── controller
│   ├── booth
│   │    ├── BoothController.java
│   │    ├── BoothProductController.java   
│   │    ├── BoothReviewController.java    
│   │    ├── BoothReservationController.java 
│   │    └── BoothNoticeController.java 
│   ├── event
│   ├── alarm
│   └── user
├── service
│   ├── booth
│   ├── event
│   ├── alarm
│   └── user
├── repository
│   ├── booth
│   ├── event
│   ├── alarm
│   └── user
└── config

```
첫 번째로 서비스, 레포, 컨트롤러의 계층 별로 분리한 뒤, 그 안에서 도메인 별 클래스를 만들어 사용하도록 합니다.

**두 번째 구조 예시**
```
com.example.projectname
├── booth
│   ├── domain
│   ├── controller
│   │    ├── BoothController.java
│   │    ├── BoothProductController.java   
│   │    ├── BoothReviewController.java    
│   │    ├── BoothReservationController.java 
│   │    └── BoothNoticeController.java 
│   ├── service
│   └── repository
├── event
│   ├── domain
│   ├── controller
│   ├── service
│   └── repository
└── user
    ├── domain
    ├── controller
    ├── service
    └── repository

```
현재 사용하는 프로젝트 구조와 비슷합니다.
단, 현재의 컨트롤러나 서비스가 권한 별로 나눠진 것을 도메인 별로 나눠지도록 수정합니다.

## Additional context

- 제가 서비스 계층에서 코어 서비스를 나눈 큰 이유는 한 컨트롤러에서 여러 서비스를 사용하고, 해당 서비스에서 또 서비스를 사용하면 순환 참조가 일어나는 원인이였는데 컨트롤러를 도메인 별로 나누어 이 점이 해결된다면 서비스도 도메인별로 하나만 사용해도 되도록 변경해 프로젝트를 구조를 덜 복잡하도록 할 수 있을 것 같습니다. 
- 둘 중 어느 방식이 마음에 드는지, 추가적으로 생각나는 방법 등 편하게 의견 주시면 감사하겠습니다.

**Comment by gitseoyeon** [comment]
저는 개인적으로 1번째 방법이 좋다고 생각합니다!다른 프로젝트들도 보면서 구조를 참고했었는데 이 구조를 사용하는것도 많이 봤고 더 봤을때도 깔끔하다는 생각이 들었습니다! 👍🏻
