### ISSUE TITLE
[SUGGEST] ResponseEntity 대신 @ResponseStatus 를 사용하도록 변경

### ISSUE THREAD

**Issue by muncool39** [Project-OpenBook/openbook-server#200]
## Description

현재 ResponseEntity 로 응답 객체를 매핑해서 보내는 방법에서,
@ResponseStatus 를 사용해 상태 코드만 추가되도록 하는 방법을 제안합니다.

**현재 사용하는 방식 (ResponseEntity)**
```java
   @PostMapping("/events")
    public ResponseEntity<ResponseMessage> registration(Authentication authentication,
                                                        @Valid EventRegistrationRequest request) {
        eventCommonService.eventRegistration(Long.valueOf(authentication.getName()), request);
        return ResponseEntity.status(HttpStatus.CREATED).body(new ResponseMessage("신청이 완료되었습니다."));
    }
```

**제안하는 방식을 사용한다면 (@ResponseStatus)**
```java
   @ResponseStatus(HttpStatus.CREATED)
   @PostMapping("/events")
    public ResponseMessage registration(Authentication authentication,
                                                        @Valid EventRegistrationRequest request) {
        eventCommonService.eventRegistration(Long.valueOf(authentication.getName()), request);
        return new ResponseMessage("신청이 완료되었습니다.");
    }
```

저희가 ResponseEntity를 사용하는 이유가 상태코드 포함 뿐이고,
응답 객체 명이 긴 경우가 많기 때문에 코드를 줄이고자 하는 이유로 제안드립니다.
## Reference

우테코 레포지토리 참고 중 발견한 내용입니다.
- https://github.com/woowacourse-teams/2024-ddangkong/blob/develop/backend/src/main/java/ddangkong/controller/room/RoomController.java
## Additional context

생각나는 점 있으시면 말씀해주세요!

**Comment by gitseoyeon** [comment]
오 이렇게 사용하면 확실히 코드도 깔끔해지고 더 보기 편할거같아서 좋은 방법인 것 같습니다!! 다른 리팩토링 작업 많으시면 저와 나눠서 해도 될 것 같네요!
