### ISSUE TITLE
[SUGGEST] 시간 데이터 타입 설정 관련 제안

### ISSUE THREAD

**Issue by gitseoyeon** [Project-OpenBook/openbook-server#21]
## Description

부스 등록 API를 구현하면서 생각나서 제안 드려봅니다!
저희가 현재 db에 datetime 이라는 데이터 타입을 지정해서 값을 넣고 있는데, datetime의 경우 날짜와 시간이 함께 저장되더라구요!
부스 등록 같은 경우는 날짜 정보는 불필요하다고 생각해서 시간 데이터만 저장하는 TIME 데이터 타입으로 변경하는 건 어떨 지 해서 제안 드려봅니다!

## Reference

https://chinggin.tistory.com/186

## Additional context

사실 스프링에서 설정하는 엔터티의 경우에는 그대로 LocalDateTime 타입을 사용하긴해서 TIME으로 설정했다고 시간 데이터만 잘려서 db에 저장될 지는 확실하지 않습니다..! ㅎㅎ 어쩌면 지금 설정한 데이터 타입이 더 괜찮은 방법일 수도 있어서, 그냥 제안일 뿐이니 의견 편하게 주세요!

**Comment by muncool39** [comment]
앗 회의에서 나왔던 내용이네요 !! 좋은 의견 감사합니다 👍
행사 기간과 부스 기간을 동일하게 가정하고 진행하고 있어서 제안하신대로 바꿔도 좋을 것 같습니다 !!
