### ISSUE TITLE
[FIX] 부스 등록 시 행사 배치 구역 엔티티에 부스 정보 추가

### ISSUE THREAD

**Issue by gitseoyeon** [Project-OpenBook/openbook-server#34]
## Description

부스를 등록할 때 행사 배치 구역 엔티티에 부스 정보와 연결된 칼럼을 추가해 해당 칼럼이 비어있을 경우 부스 정보를 저장하는 기능
## TODO

- [x] 행사 배치 구역 엔티티에 부스 칼럼 추가
- [x] 부스 등록 시 추가한 칼럼에 부스 정보 저장

**Comment by muncool39** [comment]
원래 개발한 기능을 수정하는 것이니 분류를 FIX 등으로 바꾸는 건 어떨까요?

**Comment by gitseoyeon** [comment]
> 원래 개발한 기능을 수정하는 것이니 분류를 FIX 등으로 바꾸는 건 어떨까요?

아 그게 더 낫겠네요! 수정하겠습니다~
